### ISSUE TITLE
Documentation: Minimum Node.js version

### ISSUE THREAD

**Issue by orimdominic** [agile8118/cpeak#1]
Hello @agile8118 Joseph, I would like to contribute to this project but I would like to know what the minimum version of Node.js supported by this framework is? 

I've looked into the documentation and the package.json file and I cannot find it. I also paid attention to the video attached but I did not hear you mention it. I think it is important for people who may want to use/contribute to the library.

Can it be included in the documentation (if possible, with a contribution guideline)

Thanks.

**Comment by agile8118** [comment]
Hi,
Thanks for your interest in the project! I will soon add a contribution guide to specify how we can take this forward together. As for the minimum version, yes we should add something to the package file. We'll figure that out later when the project progresses a bit because it is still in development, and we intend to use as many modern features of Node.js and JavaScript as possible. Thanks again!

**Comment by orimdominic** [comment]
You're welcome.
